CREATE OR REPLACE PACKAGE PA_Empleado IS
	FUNCTION ADD_PEDIDO RETURN SYSREFCURSOR;
	FUNCTION MOD_PEDIDO RETURN SYSREFCURSOR;
	FUNCTION DEL_PEDIDO RETURN SYSREFCURSOR;
	FUNCTION ADD_PERMISO RETURN SYSREFCURSOR;
	FUNCTION MOD_PERMISO RETURN SYSREFCURSOR;
	FUNCTION DEL_PERMISO RETURN SYSREFCURSOR;
	FUNCTION RET_MES RETURN SYSREFCURSOR;
END PA_Empleado;



CREATE OR REPLACE PACKAGE PA_Experto IS
	FUNCTION ADD_PEDIDO RETURN SYSREFCURSOR;
	FUNCTION MOD_PEDIDO RETURN SYSREFCURSOR;
	FUNCTION DEL_PEDIDO RETURN SYSREFCURSOR;
	FUNCTION ADD_PERMISO RETURN SYSREFCURSOR;
	FUNCTION MOD_PERMISO RETURN SYSREFCURSOR;
	FUNCTION DEL_PERMISO RETURN SYSREFCURSOR;
	FUNCTION ADD_ESTADO RETURN SYSREFCURSOR;
	FUNCTION MOD_ESTADO RETURN SYSREFCURSOR;
	FUNCTION DEL_ESTADO RETURN SYSREFCURSOR;
	FUNCTION ADD_PIEZA RETURN SYSREFCURSOR;
	FUNCTION MOD_PIEZA RETURN SYSREFCURSOR;
	FUNCTION DEL_PIEZA RETURN SYSREFCURSOR;
	FUNCTION ADD_REVISA RETURN SYSREFCURSOR;	
END PA_Experto;



CREATE OR REPLACE PACKAGE PA_JefePersonal IS
	FUNCTION ADD_EMPLEADO RETURN SYSREFCURSOR;
	FUNCTION MOD_EMPLEADO RETURN SYSREFCURSOR;
	FUNCTION DEL_EMPLEADO RETURN SYSREFCURSOR;
	FUNCTION ADD_EXPERTO RETURN SYSREFCURSOR;
	FUNCTION MOD_EXPERTO RETURN SYSREFCURSOR;
	FUNCTION DEL_EXPERTO RETURN SYSREFCURSOR;
	FUNCTION ADD_DIRECTO RETURN SYSREFCURSOR;
	FUNCTION MOD_DIRECTO RETURN SYSREFCURSOR;
	FUNCTION DEL_DIRECTO RETURN SYSREFCURSOR;
END PA_JefePersonal;



CREATE OR REPLACE PACKAGE PA_JefeInventarios IS
	FUNCTION ADD_BODEGA RETURN SYSREFCURSOR;
	FUNCTION MOD_BODEGA RETURN SYSREFCURSOR;
	FUNCTION DEL_BODEGA RETURN SYSREFCURSOR;
	FUNCTION ADD_INVENTARIO RETURN SYSREFCURSOR;
	FUNCTION MOD_INVENTARIO RETURN SYSREFCURSOR;
	FUNCTION DEL_INVENTARIO RETURN SYSREFCURSOR;
	FUNCTION ADD_REVISA RETURN SYSREFCURSOR;
	FUNCTION MOD_REVISA RETURN SYSREFCURSOR;
	FUNCTION DEL_REVISA RETURN SYSREFCURSOR;
	FUNCTION MOD_PROVEE RETURN SYSREFCURSOR;
	FUNCTION ADD_CONTIENE RETURN SYSREFCURSOR;
	FUNCTION MOD_CONTIENE RETURN SYSREFCURSOR;
	FUNCTION DEL_CONTIENE RETURN SYSREFCURSOR;
END PA_JefeInventarios;



CREATE OR REPLACE PACKAGE PA_Empresa IS
	FUNCTION ADD_PROVEEDOR RETURN SYSREFCURSOR;
	FUNCTION MOD_PROVEEDOR RETURN SYSREFCURSOR;
	FUNCTION DEL_PROVEEDOR RETURN SYSREFCURSOR;
	FUNCTION ADD_EMPRESA RETURN SYSREFCURSOR;
	FUNCTION MOD_EMPRESA RETURN SYSREFCURSOR;
	FUNCTION DEL_EMPRESA RETURN SYSREFCURSOR;
	FUNCTION MOD_PROVEE RETURN SYSREFCURSOR;
END PA_Empresa;



CREATE OR REPLACE PACKAGE PA_PersonaNatural IS
	FUNCTION ADD_PROVEEDOR RETURN SYSREFCURSOR;
	FUNCTION MOD_PROVEEDOR RETURN SYSREFCURSOR;
	FUNCTION DEL_PROVEEDOR RETURN SYSREFCURSOR;
	FUNCTION ADD_EMPRESA RETURN SYSREFCURSOR;
	FUNCTION MOD_EMPRESA RETURN SYSREFCURSOR;
	FUNCTION DEL_EMPRESA RETURN SYSREFCURSOR;
	FUNCTION MOD_PROVEE RETURN SYSREFCURSOR;
END PA_PersonaNatural;