CREATE OR REPLACE PACKAGE BODY PA_Empleado IS
	FUNCTION ADD_PEDIDO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PERMISOS.Adicionar_Pedido;
		RETURN X;
	END;
	FUNCTION MOD_PEDIDO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PERMISOS.Modificar_Pedido;
		RETURN X;
	END;
	FUNCTION DEL_PERMISO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PERMISOS.Eliminar_Pedido;
		RETURN X;
	END;
	FUNCTION ADD_PERMISO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PERMISOS.Adicionar_Permiso;
		RETURN X;
	END;
	FUNCTION MOD_PERMISO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PERMISOS.Modificar_Permiso;
		RETURN X;
	END;
	FUNCTION DEL_PPERMISO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PERMISOS.Eliminar_Permiso;
		RETURN X;
	END;
	
	FUNCTION RET_MES RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PERMISOS.Retiros_Mensuales
		RETURN X
	END;
	
END PA_Empleado;



CREATE OR REPLACE PACKAGE BODY PA_Empleado IS
	FUNCTION ADD_PEDIDO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PERMISOS.Adicionar_Pedido;
		RETURN X;
	END;
	
	FUNCTION MOD_PEDIDO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PERMISOS.Modificar_Pedido;
		RETURN X;
	END;
	
	FUNCTION DEL_PERMISO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PERMISOS.Eliminar_Pedido;
		RETURN X;
	END;
	
	FUNCTION ADD_PERMISO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PERMISOS.Adicionar_Permiso;
		RETURN X;
	END;
	
	FUNCTION MOD_PERMISO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PERMISOS.Modificar_Permiso;
		RETURN X;
	END;
	
	FUNCTION DEL_PPERMISO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PERMISOS.Eliminar_Permiso;
		RETURN X;
	END;
	
	FUNCTION ADD_ESTADO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_ESTADO.Adicionar_Estado;
		RETURN X;
	END;
	
	FUNCTION MOD_ESTADO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_ESTADO.Modificar_Estado;
		RETURN X;
	END;
	
	FUNCTION DEL_ESTADO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_ESTADO.Eliminar_Estado;
		RETURN X;
	END;
	
	FUNCTION ADD_PIEZA RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_ESTADO.Adicionar_Pieza;
		RETURN X;
	END;
	
	FUNCTION MOD_PIEZA RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_ESTADO.Modificar_Pieza;
		RETURN X;
	END;
	
	FUNCTION DEL_PIEZA RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_ESTADO.Eliminar_Pieza;
		RETURN X;
	END;
	
	FUNCTION ADD_REVISA RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_INVENTARIOS.Adicionar_Revisa;
		RETURN X;
	END;
	
END PA_Empleado;



CREATE OR REPLACE PACKAGE BODY PA_JefePersonal IS
	FUNCTION ADD_EMPLEADO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_EMPLEADOS.Adicionar_Empleado;
		RETURN X;
	END;
	
	FUNCTION MOD_EMPLEADO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_EMPLEADOS.Modificar_Empleado;
		RETURN X;
	END;
	
	FUNCTION DEL_EMPLEADO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_EMPLEADOS.Eliminar_Empleado;
		RETURN X;
	END;
	
	FUNCTION ADD_EXPERTO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_EMPLEADOS.Adicionar_Experto;
		RETURN X;
	END;
	
	FUNCTION MOD_EXPERTO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_EMPLEADOS.Modificar_Experto;
		RETURN X;
	END;
	
	FUNCTION DEL_EXPERTO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_EMPLEADOS.Eliminar_Experto;
		RETURN X;
	END;
	
	FUNCTION ADD_DIRECTO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_EMPLEADOS.Adicionar_Directo;
		RETURN X;
	END;
	
	FUNCTION MOD_DIRECTO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_EMPLEADOS.Modificar_Directo;
		RETURN X;
	END;
	
	FUNCTION DEL_DIRECTO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_EMPLEADOS.Eliminar_Directo;
		RETURN X;
	END;
	
END PA_JefePersonal;



CREATE OR REPLACE PACKAGE BODY PA_Empleado IS
	FUNCTION ADD_BODEGA RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_INVENTARIOS.Adicionar_Bodega;
		RETURN X;
	END;
	
	FUNCTION MOD_BODEGA RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_INVENTARIOS.Modificar_Bodega;
		RETURN X;
	END;
	
	FUNCTION DEL_BODEGA RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_INVENTARIOS.Eliminar_Bodega;
		RETURN X;
	END;
	
	FUNCTION ADD_INVENTARIO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_INVENTARIOS.Adicionar_Inventario;
		RETURN X;
	END;
	
	FUNCTION MOD_INVENTARIO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_INVENTARIOS.Modificar_Inventario;
		RETURN X;
	END;
	
	FUNCTION DEL_INVENTARIO RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_INVENTARIOS.Eliminar_Inventario;
		RETURN X;
	END;
	
	FUNCTION ADD_REVISA RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_INVENTARIOS.Adicionar_Revisa;
		RETURN X;
	END;
	
	FUNCTION MOD_REVISA RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_INVENTARIOS.Modificar_Revisa;
		RETURN X;
	END;
	
	FUNCTION DEL_REVISA RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_INVENTARIOS.Eliminar_Revisa;
		RETURN X;
	END;
	
	FUNCTION MOD_PROVEE RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PROVEEDOR.Modificar_Provee;
		RETURN X;
	END;
	
	FUNCTION ADD_CONTIENE RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_INVENTARIOS.Adicionar_Contiene;
		RETURN X;
	END;
	
	FUNCTION MOD_CONTIENE RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_INVENTARIOS.Modificar_Contiene;
		RETURN X;
	END;
	
	FUNCTION DEL_CONTIENE RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_INVENTARIOS.Eliminar_Contiene;
		RETURN X;
	END;
	
END PA_Empleado;



CREATE OR REPLACE PACKAGE BODY PA_Empresa IS
	FUNCTION ADD_PROVEEDOR RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PROVEEDOR.Adicionar_Proveedor;
		RETURN X;
	END;
	
	FUNCTION MOD_PROVEEDOR RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PROVEEDOR.Modificar_Proveedor;
		RETURN X;
	END;
	
	FUNCTION DEL_PROVEEDOR RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PROVEEDOR.Eliminar_Proveedor;
		RETURN X;
	END;
	
	FUNCTION ADD_EMPRESA RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PROVEEDOR.Adicionar_Empresa;
		RETURN X;
	END;
	
	FUNCTION MOD_EMPRESA RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PROVEEDOR.Modificar_Empresa;
		RETURN X;
	END;
	
	FUNCTION DEL_EMPRESA RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PROVEEDOR.Eliminar_Empresa;
		RETURN X;
	END;
	
	FUNCTION MOD_PROVEE RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PROVEEDOR.Modificar_Provee;
		RETURN X;
	END;
	
END PA_Empresa;



CREATE OR REPLACE PACKAGE BODY PA_Empresa IS
	FUNCTION ADD_PROVEEDOR RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PROVEEDOR.Adicionar_Proveedor;
		RETURN X;
	END;
	
	FUNCTION MOD_PROVEEDOR RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PROVEEDOR.Modificar_Proveedor;
		RETURN X;
	END;
	
	FUNCTION DEL_PROVEEDOR RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PROVEEDOR.Eliminar_Proveedor;
		RETURN X;
	END;
	
	FUNCTION ADD_PERSONA_NATURAL RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PROVEEDOR.Adicionar_Natural;
		RETURN X;
	END;
	
	FUNCTION MOD_PERSONA_NATURAL RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PROVEEDOR.Modificar_Natural;
		RETURN X;
	END;
	
	FUNCTION DEL_PERSONA_NATURAL RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PROVEEDOR.Eliminar_Natural;
		RETURN X;
	END;
	
	FUNCTION MOD_PROVEE RETURN SYSREFCURSOR IS X SYSREFCURSOR;
	BEGIN
		X := PC_PROVEEDOR.Modificar_Provee;
		RETURN X;
	END;
	
END PA_Empresa;
